controllerManager:
  repository: weiyuanke/kube-stack
  tag: "v0.1.3"
grafana:
  repository: grafana/grafana
  tag: "9.5.12"
prometheus:
  repository: bitnami/prometheus
  tag: "2.47.1"
global:
  imageRegistry: docker.m.daocloud.io # docker.io
  inClusterMode: true
  kubeConfigSecretName: ""
  kubeConfigSecretKey: ""
  nodeSelector: {}
tlsCertsSecretName: ""
kubernetesClusterDomain: cluster.local